version: '3.9'
services:
    app:
        build: .
        depends_on:
            db:
                condition: service_healthy
        restart: always
        ports: 
            - 8000:8000
        volumes:
            - ./inst_back/media:/code/inst_back/media
        env_file: .env
    db:
        image: postgres
        restart: always
        volumes:
            - ./database/data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: insta_db
            POSTGRES_USER: django_logic
            POSTGRES_PASSWORD: djlg3000
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U django_logic -d insta_db"]
            interval: 10s
            timeout: 5s
            retries: 5
    redis:
        image: redis:5
        restart: always
       